[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "1.4.2"
numpy = "1.21.5"
python = "^3.8"
scipy = "1.7.3"
matplotlib = "3.5.1"
